version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/java"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions" # GitHub Actions自体の更新も自動化
    directory: "/"
    schedule:
      interval: "weekly"
