name: Build Gradle project

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup dependencies
        uses: ./.github/actions/build-deps

      - name: Make gradlew executable
        run: chmod +x java/gradlew

      - name: Run gradle build
        run: |
          cd java
          nix develop --command ./gradlew build
